id: 4f565780c1bc48c2a20ecc2949cd825a
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_11-The_Transcendent_Perfection_of_Wisdom_in_Ten_Thousand_Lines-v1
  language: en
  author: ''
  volume: {}
